### ISSUE TITLE
Does't work on MIUI11 Android10

### ISSUE THREAD

**Issue by icew4y** [NVISO-BE/MagiskTrustUserCerts#12]
module installed
cert installed
reboot 
does't work
cannot find user cert in system storage

**Comment by TheDauntless** [comment]
I just pushed an update to the repo. Can you try this one out?

**Comment by icew4y** [comment]
> I just pushed an update to the repo. Can you try this one out?

ok,thanks,trying

**Comment by icew4y** [comment]
> I just pushed an update to the repo. Can you try this one out?

it  does't work

**Comment by TheDauntless** [comment]
Thanks for checking. The Magisk modules structure changed and I think they overlooked the use-case of this plugin, or there's a bug in Magisk. I'm waiting on an issue I opened at the Magisk github.

**Comment by TheDauntless** [comment]
Can you try out v0.4.1 I just pushed?

**Comment by icew4y** [comment]
> Can you try out v0.4.1 I just pushed?

This time it worked!thank you, awesome work!
