### ISSUE TITLE
does it work for Android 9?

### ISSUE THREAD

**Issue by fiestyqier** [NVISO-BE/MagiskTrustUserCerts#5]
Hi, anyone tried it on Android 9 and was it working?
I have followed the installation steps on a Android 9 device but was unable to find `/magisk/trustusercerts/ ` and my user certificates did not show up in the system wide trust store.

**Comment by sunu11** [comment]
me too .it can't working on Android 9.

**Comment by giacomoferretti** [comment]
I don't have any problems with this module. Have you rebooted?

Tested on Android 9 and Android 10.

**Comment by acornsirup** [comment]
I'm not quite sure what the core issue is, but on Android 9 (LineageOS 16.0 20200418 on OnePlus 2), the CA cert is copied correctly into the system certificate store, but it isn't trusted.

Verified by alternatively installing it manually (http://wiki.cacert.org/FAQ/ImportRootCert#Android_Phones_.26_Tablets).

So the problem doesn't seem to be this module but something concerning the different Android flavours. Hm.

**Comment by giacomoferretti** [comment]
Works fine for me. Android 9 and 10.
